### ISSUE TITLE
ci needs to be fixed...

### ISSUE THREAD

**Issue by flaribbit** [flaribbit/vitepress-theme-sakura#8]
This project also needs a major update...

**Comment by flaribbit** [comment]
立个 flag🚩，周末一定修！

**Comment by WRXinYue** [comment]
最近发现了一个博客系统 [Valaxy](https://valaxy.site/)，使用体验非常友好，在性能和扩展性方面表现出色。通常我会选择使用 VitePress 来构建文档系统，因为它在这一领域的特性更加符合需求。但对于博客建设而言，Valaxy 显得更加简洁高效。

**Comment by flaribbit** [comment]
> 最近发现了一个博客系统 [Valaxy](https://valaxy.site/)，使用体验非常友好，在性能和扩展性方面表现出色。通常我会选择使用 VitePress 来构建文档系统，因为它在这一领域的特性更加符合需求。但对于博客建设而言，Valaxy 显得更加简洁高效。

确实，我了解那个框架和它的作者，我也会向其他新人推荐 Valaxy 框架。

但是我个人喜欢搞 minimal 的东西（

**Comment by WRXinYue** [comment]
> > 最近发现了一个博客系统 [Valaxy](https://valaxy.site/)，使用体验非常友好，在性能和扩展性方面表现出色。通常我会选择使用 VitePress 来构建文档系统，因为它在这一领域的特性更加符合需求。但对于博客建设而言，Valaxy 显得更加简洁高效。
> 
> 确实，我了解那个框架和它的作者，我也会向其他新人推荐 Valaxy 框架。
> 
> 但是我个人喜欢搞 minimal 的东西（

赞同你的看法。在我创建 valaxy-theme-sakura 之前，我将会持续对这个项目进行优化和完善，尤其是在性能方面。

**Comment by flaribbit** [comment]
> 赞同你的看法。在我创建 valaxy-theme-sakura 之前，我将会持续对这个项目进行优化和完善，尤其是在性能方面。

直接开坑吧，这仓库的代码我自己都看不下去了（）

**Comment by WRXinYue** [comment]
> > 赞同你的看法。在我创建 valaxy-theme-sakura 之前，我将会持续对这个项目进行优化和完善，尤其是在性能方面。
> 
> 直接开坑吧，这仓库的代码我自己都看不下去了（）

多点自信，代码就是用来不断迭代和优化的)
